package jm.task.core.jdbc.dao;

import jm.task.core.jdbc.model.User;
import jm.task.core.jdbc.util.Util;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class UserDaoJDBCImpl implements UserDao {
    public UserDaoJDBCImpl() {
    }

    public void createUsersTable() {

        String sql = "CREATE TABLE IF NOT EXISTS Users (" + //создаем таблицу если не существует
                "id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, " +  // указывает на первичность ключа, либо сериал для автоинкреминтирования
                "name VARCHAR(100) NOT NULL, " + //хранение имени
                "lastName VARCHAR(100), " +
                "age SMALLINT)";  // смалинт -32,768 до 32,767
        try (Connection connection = Util.getConnection();
             Statement statement = connection.createStatement()) { //создаем соединение для
            statement.executeUpdate(sql); //выполнения эскуэль запросов
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.println("Ошибка при создании таблицы");
        }
    }

    public void dropUsersTable() {

        String sql = "DROP TABLE IF EXISTS Users";
        try (Connection connection = Util.getConnection();
             Statement statement = connection.createStatement()) {
            statement.executeUpdate(sql);
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.println("Ошибка при удалении таблицы");
        }
    }

    public void saveUser(String name, String lastName, byte age) {

        String sql = "INSERT INTO Users (name, lastName, age) VALUES (?, ?, ?)";
        try (Connection connection = Util.getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(sql)) {
            preparedStatement.setString(1, name);
            preparedStatement.setString(2, lastName);
            preparedStatement.setByte(3, age);
            preparedStatement.executeUpdate();
            System.out.println("User с именем – " + name + " добавлен в базу данных");
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.println("Ошибка при добавлении пользователя");
        }
    }

    public void removeUserById(long id) {

        String sql = "DELETE FROM Users WHERE id = ?";
        try (Connection connection = Util.getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(sql)) {
            preparedStatement.setLong(1, id);
            preparedStatement.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.println("Ошибка при удалении пользователя");
        }
    }

    public List<User> getAllUsers() {
        List<User> users = new ArrayList<>();
        String sql = "SELECT * FROM Users"; //извлекает всех пользователей
        try (Connection connection = Util.getConnection();
             Statement statement = connection.createStatement();
             ResultSet resultSet = statement.executeQuery(sql)) { //получаем резульаты

            while (resultSet.next()) {
                User user = new User();
                user.setId(resultSet.getLong("id"));
                user.setName(resultSet.getString("name"));
                user.setLastName(resultSet.getString("lastName"));
                user.setAge((byte) resultSet.getShort("age"));

                users.add(user);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.println("Ошибка при получении списка пользователей");
        }
        return users;
    }
    //    return null;


    public void cleanUsersTable() {
        String sql = "TRUNCATE TABLE Users";
        try (Connection connection = Util.getConnection();
             Statement statement = connection.createStatement()) {
            statement.executeUpdate(sql);
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.println("Ошибка при очистке таблицы пользователей");
        }
    }
}
